-- COALESCE(FREEZER_YN, 'N') : 값들 중 NULL이 아닌 첫번 째 값
-- ADDRESS LIKE '%경기%' : 경기가 포함된 값
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS, COALESCE(FREEZER_YN, 'N') AS FREEZER_YN
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE '%경기%'
ORDER BY WAREHOUSE_ID