-- LIMIT : 보여줄 개수
-- ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) : ORDER BY에도 DATEDIFF 사용 가능
-- 보호 기간이 가장 길었던 동물 두 마리의 아이디와 이름을 조회
-- 보호 기간이 긴 순으로 조회
SELECT I.ANIMAL_ID, I.NAME
FROM ANIMAL_INS I
JOIN ANIMAL_OUTS O USING (ANIMAL_ID)
ORDER BY DATEDIFF(O.DATETIME, I.DATETIME) DESC
LIMIT 2