-- 음식종류별로 즐겨찾기수가 가장 많은 식당의 음식 종류, ID, 식당 이름, 즐겨찾기수를 조회
-- 음식 종류를 기준으로 내림차순 정렬
-- 서브 쿼리를 사용하여 (FOOD_TYPE, FAVORITES)와 일치하는 FAVORITES가 가장 큰 값 찾기
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
WHERE (FOOD_TYPE, FAVORITES) IN
(SELECT FOOD_TYPE, MAX(FAVORITES) FROM REST_INFO GROUP BY FOOD_TYPE)
ORDER BY FOOD_TYPE DESC

/*
아래와 같이 구현하면 각 FOOD_TYPE의 첫번쨰 행이 결과로 나옴
SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM REST_INFO
GROUP BY FOOD_TYPE HAVING FAVORITES = MAX(FAVORITES)
ORDER BY FOOD_TYPE DESC
*/