-- IFNULL(TLNO, 'NONE') AS TLNO : TLNO이 NULL이면 'NONE'으로 넣기, AS는 열 이름 바꾸기
SELECT PT_NAME, PT_NO, GEND_CD, AGE, IFNULL(TLNO, 'NONE') AS TLNO
FROM PATIENT
WHERE AGE <= 12 AND GEND_CD ='W'
ORDER BY AGE DESC, PT_NAME