-- SELECT MAX(PRICE) AS PRICE FROM FOOD_PRODUCT : 이 코드로 MAX값 찾기
SELECT *
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) AS PRICE FROM FOOD_PRODUCT)

/*
해당 코드는 PRICE만 MAX값이고 나머지 값은 상관없는 값이 리턴됨
SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, MAX(PRICE) AS PRICE
FROM FOOD_PRODUCT
*/